version: "2"

networks:
  luby_cash:
    external: true

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - luby_cash
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    networks:
      - luby_cash
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "new-user:1:1,update-user:1:1,delete-user:1:1,add-permission:1:1,forgot-password:1:1,redefine-password:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock