version: "3"

volumes:
  db-data:

networks:
  luby_cash:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3002:3002"
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    networks:
      - luby_cash
    depends_on:
      - mysql-api
  mysql-api:
    build:
      context: ./docker/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: luby_cash_api
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - luby_cash